apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-by-mahdi
  namespace: apps
  labels:
    app: container-by-mahdi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: container-by-mahdi
  template:
    metadata:
      labels:
        app: container-by-mahdi
    spec:
      containers:
      - name: do-k8s-ghactions-mahdi
        image: registry.digitalocean.com/containers/do-k8s-ghactions:latest
        ports:
        - containerPort: 80
