name: Build and push container to docker repo containers @ DO
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Login to Digital Ocean Registry
      uses: docker/login-action@v3
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

    - name: Build latest
      run: docker build -t registry.digitalocean.com/containers/do-k8s-ghactions:$(echo $GITHUB_SHA | head -c7) .

    - name: Push to Digital Ocean
      run: docker push registry.digitalocean.com/containers/do-k8s-ghactions:$(echo $GITHUB_SHA | head -c7)

      # Set up the Kubernetes CLI with your DigitalOcean Kubernetes cluster.

    - name: Set up kubectl
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        clusterName: k8s-bergen
        expirationTime: "1200"

    # Run any kubectl commands you want!
    - name: Get nodes
      run: kubectl get nodes